font:
  normal:
    family: WenQuanYiZenHeiMono Nerd Font
colors:
  normal:
    black:   '0x282a36'
    red:     '0xff5c57'
    green:   '0x5af78e'
    yellow:  '0xf3f99d'
    blue:    '0x57c7ff'
    magenta: '0xff6ac1'
    cyan:    '0x9aedfe'
    white:   '0xf1f1f0'
  bright:
    black:   '0x686868'
    red:     '0xff5c57'
    green:   '0x5af78e'
    yellow:  '0xf3f99d'
    blue:    '0x57c7ff'
    magenta: '0xff6ac1'
    cyan:    '0x9aedfe'
    white:   '0xeff0eb'
background_opacity: 0.5
