ln -sf "$APP_DIRNAME/locale.json" "$HOME/Library/Application Support/Code/User"
ln -sf "$APP_DIRNAME/settings.json" "$HOME/Library/Application Support/Code/User"
ln -sf "$APP_DIRNAME/keybindings.json" "$HOME/Library/Application Support/Code/User"

code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension EditorConfig.EditorConfig
code --install-extension GitHub.vscode-pull-request-github
code --install-extension Gruntfuggly.todo-tree
code --install-extension PKief.markdown-checkbox
code --install-extension PKief.material-icon-theme
code --install-extension SirTori.indenticator
code --install-extension Tyriar.sort-lines
code --install-extension auchenberg.vscode-browser-preview
code --install-extension bierner.emojisense
code --install-extension bierner.markdown-emoji
code --install-extension bierner.markdown-preview-github-styles
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension deerawan.vscode-faker
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-debug-launcher
code --install-extension fabiospampinato.vscode-statusbar-debugger
code --install-extension geddski.macros
code --install-extension jasonnutter.search-node-modules
code --install-extension kamikillerto.vscode-colorize
code --install-extension mkxml.vscode-filesize
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-ssh-explorer
code --install-extension nhoizey.gremlins
code --install-extension patrys.vscode-code-outline
code --install-extension pnp.polacode
code --install-extension qinjia.view-in-browser
code --install-extension redhat.vscode-yaml
code --install-extension richie5um2.vscode-sort-json
code --install-extension ryu1kn.partial-diff
code --install-extension seeker-dk.node-modules-viewer
code --install-extension sgtsquiggs.vscode-active-file-status
code --install-extension silvenon.mdx
code --install-extension sohamkamani.code-eol
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tokoph.ghosttext
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension wmaurer.change-case
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.Material-theme
